package com.risetek.scada.db;

/*
 * Data Points
 * create table dataPoints (
 * id int not null generated by default as identity (start with 1, increment by 1),
 * dataSourceId int not null,
 * data blob not null
 * );
 * alter table dataPoints add constraint dataPointsPk primary key (id);
 * alter table dataPoints add constraint dataPointsFk1 foreign key (dataSourceId) references dataSources(id);
 */
import javax.jdo.annotations.IdGeneratorStrategy;
import javax.jdo.annotations.IdentityType;
import javax.jdo.annotations.PersistenceCapable;
import javax.jdo.annotations.Persistent;
import javax.jdo.annotations.PrimaryKey;

import com.google.appengine.api.datastore.Blob;

@PersistenceCapable(identityType = IdentityType.APPLICATION)
public class dataPoints {
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public int getDataSourceId() {
		return dataSourceId;
	}
	public void setDataSourceId(int dataSourceId) {
		this.dataSourceId = dataSourceId;
	}
	public Blob getBlob() {
		return blob;
	}
	public void setBlob(Blob blob) {
		this.blob = blob;
	}
	
	public dataPoints(int dataSourceId, Blob blob) {
		this.dataSourceId = dataSourceId;
		this.blob = blob;
	}
	@PrimaryKey
    @Persistent(valueStrategy = IdGeneratorStrategy.IDENTITY)
	private Long id;
	@Persistent
	private int dataSourceId;
	@Persistent
	private Blob blob;
}
