package com.risetek.scada.db;

import javax.jdo.annotations.IdGeneratorStrategy;
import javax.jdo.annotations.IdentityType;
import javax.jdo.annotations.PersistenceCapable;
import javax.jdo.annotations.Persistent;
import javax.jdo.annotations.PrimaryKey;
import com.google.appengine.api.datastore.Blob;

/*
 * Data Sources
 * create table dataSources (
 * id int not null generated by default as identity (start with 1, increment by 1),
 * name varchar(40) not null,
 * dataSourceType int not null,
 * data blob not null
 * );
 * alter table dataSources add constraint dataSourcesPk primary key (id);
 */

@PersistenceCapable(identityType = IdentityType.APPLICATION)
public class dataSources {

	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public int getDataSourceType() {
		return dataSourceType;
	}
	public void setDataSourceType(int dataSourceType) {
		this.dataSourceType = dataSourceType;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public Blob getData() {
		return data;
	}
	public void setData(Blob data) {
		this.data = data;
	}
	public dataSources(int dataSourceType, String name, Blob data) {
		this.dataSourceType = dataSourceType;
		this.name = name;
		this.data = data;
	}
	
	@PrimaryKey
    @Persistent(valueStrategy = IdGeneratorStrategy.IDENTITY)
	private Long id;
	@Persistent
	private int dataSourceType;
	@Persistent
	private String name;
	@Persistent
	private Blob data;
}
