application: risedius
version: 1
runtime: python
api_version: 1

handlers:

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /forms/.*
  script: main.py

- url: /(.*)
  static_files: static/\1
  upload: static/(.*)

