application: risedius
version: 1
runtime: python
api_version: 1

handlers:

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /favicon.ico
  static_files: static/images/favicon.ico
  mime_type: application/octet-stream
  upload: static/images/favicon.ico

- url: /httping.jar
  static_files: static/httping.jar
  mime_type: application/octet-stream
  upload: static/httping.jar

- url: /forms/.*
  script: main.py

- url: /(.*)
  static_files: static/\1
  upload: static/(.*)

